import { existsSync, lstatSync } from 'fs';
import { readFile } from 'node:fs';
import { transform } from '@babel/core';
import { add, double } from "./lib/numbers.ts";
import { double1 } from "./lib/numbersx.ts";
import { double2 } from "./lib/numbers2";
import { double3 } from "./lib/numbers3.js";
import { double4 } from "./lib/numbers4.jsx";
import component from "./component.style.ts";
import png from './logo.png';
import * as Something from './lib/something';
import * as SomethingTest from './lib/something.test';
export { something as another } from '/lib/something';
import { export1 , export2 as alias2 } from './lib/something/';
import { oneBackLevel } from '..';
import { oneBackLevelIndex } from '../';
import { twoBackLevel } from '../..';
import { twoBackLevelIndex } from '../../';
export { oneBackLevel } from '..';
export { oneBackLevelIndex } from '../';
export { twoBackLevel } from '../..';
export { twoBackLevelIndex } from '../../';
export { add, double } from "./lib/numbers.main";