import { existsSync, lstatSync } from 'fs';
import { readFile } from 'node:fs';
import { transform } from '@babel/core';
import { add, double } from "./lib/numbers.ts";
import { double1 } from "./lib/numbersx.ts";
import { double2 } from "./lib/numbers2.js";
import { double3 } from "./lib/numbers3.js";
import { double4 } from "./lib/numbers4.jsx";
import component from "./component.style.ts";
import png from "./logo.png.js";
import * as Something from "./lib/something.js";
import * as SomethingTest from "./lib/something.test.js";
export { something as another } from '/lib/something';
import { export1, export2 as alias2 } from "./lib/something/index.js";
import { oneBackLevel } from "../index.js";
import { oneBackLevelIndex } from "../index.js";
import { twoBackLevel } from "../../index.js";
import { twoBackLevelIndex } from "../../index.js";
export { oneBackLevel } from "../index.js";
export { oneBackLevelIndex } from "../index.js";
export { twoBackLevel } from "../../index.js";
export { twoBackLevelIndex } from "../../index.js";
export { add, double } from "./lib/numbers.main.js";